kind: Service
apiVersion: v1
metadata:
  name: "exchangeratesapi"
spec:
  selector:
    app: "exchangeratesapi-deployment"
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: ClusterIP